openCollection: 1.0.0
type: environment
name: local
variables:
  baseURL: http://localhost:8000
  token: ""
  eventID: ""
  ticketTypeID: ""
  seatID: ""
  seatID2: ""
  reservationID: ""
  idempotencyKey: manual-test-key
  email: student@example.com
  password: very-secure-password
